import Link from "next/link";
import { MATCH_COMPONENTS } from "@/matching/rank";

export const metadata = { title: "How it works — Agents Date" };

const STEPS = [
  {
    title: "1. Two links per person",
    body: "One LinkedIn profile and one public Instagram profile. A company page or an Instagram post link is rejected, because a person is required.",
  },
  {
    title: "2. Capture what the profile actually shows",
    body: "Apify's official Instagram actor when a token is configured; otherwise the person pastes their own visible profile text, which is the credential-free consented path.",
  },
  {
    title: "3. Analyse, with a citation on every claim",
    body: "Each line is classified, then matched against a shared trait taxonomy. A trait that appears on both sources scores higher. Nothing is claimed without a quote and a line number.",
  },
  {
    title: "4. Say what is unknown",
    body: "Age, orientation, relationship status and availability appear in neither source, so the agent refuses to guess. Gaps are shown on the profile page.",
  },
  {
    title: "5. The agents date",
    body: "Two agents alternate: open from the other person's evidence, build shared ground, name a real tension, then reflect. Turns carry the evidence that prompted them.",
  },
  {
    title: "6. Rank who fits best",
    body: "Scoring is directed. A's ranking of B is not B's ranking of A, because needs and what each person brings differ.",
  },
];

export default function MethodPage() {
  return (
    <main>
      <h1>How it works</h1>
      <p className="lede">
        Every person is represented by an agent that reads exactly two public profiles, and the agents date each other.
        This page is the honest version of that claim, including where it stops.
      </p>

      <div className="grid grid-2" style={{ marginTop: 22 }}>
        {STEPS.map((s) => (
          <section className="panel" key={s.title}>
            <h3>{s.title}</h3>
            <p className="small mb0">{s.body}</p>
          </section>
        ))}
      </div>

      <section className="panel" style={{ marginTop: 16 }}>
        <h2>Measured limits of public-profile capture</h2>
        <p className="small">
          These were tested directly against the live services while building this project, not assumed.
        </p>
        <div className="grid grid-2">
          <div>
            <span className="chip chip-bad">LinkedIn · HTTP 999</span>
            <p className="small mt16 mb0">
              LinkedIn returns status 999, its bot-block response, for anonymous automated requests, on every user
              agent tried. LinkedIn&apos;s User Agreement (s8.2) also prohibits scraping or copying profile data
              without the content owner&apos;s consent. The Apify LinkedIn adapter in this repo is therefore
              <b> disabled by default</b> and must stay that way without documented permission.
            </p>
          </div>
          <div>
            <span className="chip chip-bad">Instagram · client-only</span>
            <p className="small mt16 mb0">
              A public profile returns HTTP 200 with a JavaScript-rendered shell containing no profile text, and the
              JSON endpoint answers 401 without auth. Capture therefore needs Apify (an official actor exists, priced
              per result) or a consented path where the person supplies their own visible text.
            </p>
          </div>
        </div>
      </section>

      <section className="panel">
        <h2>Scoring model</h2>
        <p className="small">
          {MATCH_COMPONENTS.length} weighted components, each shown with its own explanation on every match card so a
          ranking can be audited rather than trusted. These weights are imported from the ranker, so this page cannot
          drift from the code.
        </p>
        <ul className="clean">
          {MATCH_COMPONENTS.map((c) => (
            <li key={c.key}>
              <b style={{ color: "var(--text)" }}>{c.label} — {Math.round(c.weight * 100)}%.</b> {c.detail}{" "}
              <span className="dim">{c.directional ? "Directed." : "Symmetric."}</span>
            </li>
          ))}
        </ul>
      </section>

      <section className="panel">
        <h2>What the agents are not</h2>
        <p className="small mb0">
          The conversations are generated by software from two public profiles. They are not written, agreed or sent by
          the people shown, and no message is ever delivered to anyone. This is a simulation of compatibility, not a
          messaging product.
        </p>
      </section>

      <div style={{ marginTop: 20, display: "flex", gap: 10, flexWrap: "wrap" }}>
        <Link className="btn btn-primary" href="/demo">
          See the completed run
        </Link>
        <Link className="btn" href="/">
          Add your own links
        </Link>
      </div>
    </main>
  );
}
