import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Agents Date — every profile has an agent that dates on their behalf",
  description:
    "Two public profiles in. One agent per person. The agents read needs, hobbies and interests, then date each other.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="shell">
          <header className="topbar">
            <Link href="/" className="brand">
              <span className="brand-dot">AI</span>
              <span>
                Agents Date
                <small>Agents read two profiles, then date on their behalf</small>
              </span>
            </Link>
            <nav className="nav">
              <Link href="/">Start</Link>
              <Link href="/demo">Live demo</Link>
              <Link href="/method">How it works</Link>
            </nav>
          </header>
          {children}
          <footer style={{ marginTop: 46, paddingTop: 20, borderTop: "1px solid var(--line)" }}>
            <p className="small dim mb0">
              Agents Date is an AI simulation built only from two public profiles per person. Conversations are
              generated by software, not written by the people shown. Do not share anyone&apos;s profile without their
              permission.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
